### ISSUE TITLE
 https://codecov.io/ vs https://coveralls.io/

### ISSUE THREAD

**Issue by Carreau** [brettcannon/cpython-ci-test#27]
In your mail on core-workflow you point toward these two services.

I'm just going to share personal experience:

 - I'm disappointed by https://coveralls.io/ and had several issue with them, at some point they were extremely unresponsive to issue, including when trying to see the coverage would redirect-loop, or ask for an increase of permission to get full read-write access to all my repositories to _view_ coverage.

-  https://codecov.io/ has on the other handbe extremly responsive to bug/questions/twitter ping. Codecov also have their browser extensions [e.g.: for chrome](https://chrome.google.com/webstore/detail/codecov-extension/keefkhehidemnokodkdkejapdgfjmijf) which display the coverage ona line-by-line basis as an overlay on GitHub. Which is _tremendouly_ useful in PR to see which lines are not covered during review.

My (biased) waiting on this, hoping it can help.

**Comment by brettcannon** [comment]
Let's try voting using reactions.

**Comment by brettcannon** [comment]
How do you feel about Codecov?
https://codecov.io/gh/brettcannon/cpython-ci-test

**Comment by brettcannon** [comment]
How do you feel about Coveralls?
https://coveralls.io/github/brettcannon/cpython-ci-test

**Comment by brettcannon** [comment]
See #32 for a sample PR to see how the tools interact with PRs (once CI is finished).

**Comment by abalkin** [comment]
Does any of these services support C code coverage?

**Comment by brettcannon** [comment]
@abalkin don't know; you can check their docs to find out (Codecov might as I saw in their Travis output a mention of gcov).

**Comment by abalkin** [comment]
It turned out I did know that about codecov - I had [C coverage published on codecov](https://codecov.io/gh/abalkin/cpython/tree/ci/Modules) for my CPython fork.  If coveralls don't have similar support I would consider it a deal-breaker.

**Comment by Carreau** [comment]
IIRC, Codecov and coverall both support xUnit coverage submission. So as long as you find (or write a tool) that spit that out, you can have coverage for it. If your tool of choice does not behave well if ran in parallel, you can store the output in various files (named by job ID ?) and use [something liek xunitmerge](https://pypi.python.org/pypi/xunitmerge/1.0) to merge the files before sending to these services. 

So even things like documentation could be covered by a spellchecker, or link checker.

**Comment by malemburg** [comment]
Is there a similar dashboard like the "recent builds" one on coveralls available on codecov as well ?

The codecov UI looks friendlier and more like github, but the "recent builds" dashboard gives a much more direct feedback on whether a PR causes the coverage to go up or down.

All I could find was this screen: https://codecov.io/gh/brettcannon/cpython-ci-test/pulls but it's nowhere near as intuitive as the coveralls one.

**Comment by Carreau** [comment]
The screens for this repository are not that great yet as it is relatively recent. You can look at project that have use codecov for longer like https://codecov.io/gh/ipython/ipython
