### ISSUE TITLE
Build docs on Circle

### ISSUE THREAD

**Issue by brettcannon** [brettcannon/cpython-ci-test#7]

**Comment by brettcannon** [comment]
It would be good if it can be done just once somehow and not on every platform.

**Comment by phdru** [comment]
You don't need the freshly built python to built docs, right? Then I think docs can be built in parallel. If you enable 2 virtual machines at Circle I'll submit a PR for building python and docs in separate VMs.

To configure VMs login to Circle with you GitHub credentials. Open settings for editing your project at https://circleci.com/gh/brettcannon/cpython-ci-test/edit. Go to "Adjust Parallelism" at https://circleci.com/gh/brettcannon/cpython-ci-test/edit#parallel-builds. Enable 2 VMs (free projects are allowed up to 4).

**Comment by brettcannon** [comment]
@phdru I set the parallelism for 3x.

**Comment by brettcannon** [comment]
And no, you don't need a checkout of Python to do a build. If you look at the Travis configuration you will notice I have it set to just run on a normal Python 3 container.

**Comment by brettcannon** [comment]
Fixed by #15
